# Generated by Django 4.1.2 on 2023-02-06 15:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学校')),
            ],
        ),
        migrations.CreateModel(
            name='Woman_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(blank=True, default='女', max_length=1, verbose_name='性别')),
                ('area', models.CharField(max_length=32, null=True, verbose_name='地区')),
                ('qq', models.IntegerField(null=True, verbose_name='QQ号')),
                ('mobile', models.CharField(max_length=32, null=True, verbose_name='电话号码')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('intro', ckeditor.fields.RichTextField(null=True, verbose_name='个人介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('photo', models.ImageField(blank=True, upload_to='static/images/box', verbose_name='照片')),
                ('cover', models.ImageField(blank=True, upload_to='', verbose_name='封面')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='box.school', verbose_name='校名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='发表者')),
            ],
        ),
        migrations.CreateModel(
            name='Man_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(blank=True, default='男', max_length=1, verbose_name='性别')),
                ('area', models.CharField(max_length=32, null=True, verbose_name='地区')),
                ('qq', models.IntegerField(null=True, verbose_name='QQ号')),
                ('mobile', models.CharField(max_length=32, null=True, verbose_name='电话号码')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('intro', ckeditor.fields.RichTextField(null=True, verbose_name='个人介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='照片')),
                ('cover', models.ImageField(blank=True, upload_to='', verbose_name='封面')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='box.school', verbose_name='校名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='发表者')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(null=True, verbose_name='评论内容')),
                ('box1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='box.woman_box', verbose_name='评论盲盒')),
                ('box2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='box.man_box', verbose_name='评论盲盒')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('pre_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='box.comment', verbose_name='父评论id')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment_tb',
            },
        ),
        migrations.CreateModel(
            name='Cltwoman_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clt_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=64)),
                ('Cltbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clt_womanbox', to='box.woman_box')),
                ('who_clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cltman_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clt_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=64)),
                ('Cltbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clt_womanbox', to='box.man_box')),
                ('who_clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
