# Generated by Django 4.1.2 on 2023-02-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_author',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentator',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
