# Generated by Django 4.1.2 on 2023-02-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='box1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='评论盲盒', to='box.woman_box'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='box2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='评论盲盒', to='box.man_box'),
        ),
    ]
